spring:

  datasource:
    url: jdbc:mysql://13.209.207.232:3306/shoppingMall?serverTimezone=Asia/Seoul
    username: scott
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

#registration

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 847587285531-qpr6svf9to71gbm5ur8ap7p1qllvra3p.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-typ: authorization_code
            scope: profile, email

          naver:
            client-name: naver
            client-id: VwPec4qUXTztkMTSNN3z
            client-secret: 6ZAcB3NQHm
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - name

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
            user-name-attribute: response



  server:
    adress: 13.125.180.49
    port: 8080
    servlet:
      session:
      timeout: 1800
      multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

logging.level:
  org.hibernate.SQL: debug






